Interface to UI for UKy
prommis/prommis pull request #26
Opened 2024-01-08 18:44 UTC by dangunter

## Addresses Issue: 

## Summary/Motivation:

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md file
   at the top level of this directory.

2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

2024-01-08 19:58 UTC, dangunter commented
Currently waiting for #25 to resolve.

2024-01-22 17:35 UTC, lbianchi-lbl requested changes
Needs `pytest.importorskip` so that the tests pass when WaterTAP (which we're treating as an optional dependency) is not installed.

2024-01-22 17:35 UTC, lbianchi-lbl commented on src/prommis/uky/tests/test_uky_flowsheet_ui.py
> +from prommis.uky import uky_flowsheet_ui as ui
```suggestion
import pytest
ui = pytest.importorskip("prommis.uky.uky_flowsheet_ui", reason="Flowsheet UI components not available")
```

2024-04-24 16:45 UTC, dangunter commented
This PR seems to be stuck due to a codecov error that has these characteristics:
* Happens every time
* Only occurs with the Linux / Python 3.11 / Dev workflow

No idea what to do next, except force merge?
Thoughts, @lbianchi-lbl?

2024-04-24 17:06 UTC, dangunter commented
OK, it works now. We should approve it quick before it breaks again.

2024-04-29 17:32 UTC, bpaul4 reviewed
@dangunter the code all works and the new content looks good, but I'm not sure how to generate the PNG file (or should it open a browser tab?). It would also be helpful if you could add some light documentation.

2024-04-29 18:35 UTC, MarcusHolly approved these changes
LGTM

2024-05-01 03:39 UTC, dangunter commented
@bpaul4 good point about the documentation, I will work on that.

I am not sure I understand the PNG question. Perhaps you are assuming it is autogenerated; it is just a picture. It should display in the initial "input" screen when that model is loaded into the WaterTAP UI.

2024-05-06 13:35 UTC, bpaul4 approved these changes
I'll trust that this works as intended, given that the tests are passing and everything looks good.

2024-05-06 17:57 UTC, merged