COST ESTIMATE OF A HYDROGEN DECREPITATION FURNACE
prommis/prommis pull request #65
Opened 2024-04-26 02:30 UTC by Akintomiwaojo

## Addresses Issue: 

## Summary/Motivation:

## Changes proposed in this PR:
-
-

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.md file
   at the top level of this directory.

2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

2024-04-26 13:58 UTC, andrewlee94 requested changes
A few questions, mostly about what this PR is meant to be adding. There are a number of files being changed that don;t look like they are related to hydrogen decrepitation, and the one file that is about the hydrogen decripitation appears to be mostly Python code and in the wrong place.

2024-04-26 13:58 UTC, andrewlee94 commented on src/prommis/HD_CE.py
> +from math import pi
For consistency, you should get do:

```
from idaes.core.util.constants import Constants
```

You can then get `pi` as `Cosntants.pi` (along with a number of other useful constants).

2024-04-26 13:58 UTC, andrewlee94 commented on src/prommis/HD_CE.py
> +from pyomo.environ import units as pyunits
Combine this with the line above, as they all come from the same place.

2024-04-26 13:58 UTC, andrewlee94 commented on src/prommis/HD_CE.py
> +                ramp_up_time = 20,                                                  #Ramp Up time (in minutes)
Standardize comment formatting - some are missing a space after the `#` . also, to fit our standard line length limitations, I suggest only using a double space before the in-line comment.

I will also note you are presuming units here which will limit generality later.

2024-04-26 13:58 UTC, andrewlee94 commented on src/prommis/HD_CE.py
> +from pyomo.environ import ConcreteModel, Constraint, Param, Var, units,PositiveReals, log
This is not the right place for this file. If it is costing related then it should go in a costing folder somewhere.

2024-04-26 13:58 UTC, andrewlee94 commented on src/prommis/HD_CE.py
> +
Excess line breaks at end of file.

2024-04-26 13:58 UTC, andrewlee94 commented on src/prommis/HD_CE.py
> +        CAPEX = self.C_Ins1()[1] + self.C_Metal1()[1] + self.C_Ins2()[1]+ self.C_Metal2()[1] + self.transformer_cost + self.temperature_controller_price+self.heating_coil() + transportation_cost + in
I am somewhat uncertain as to what the purpose of this file is - for the most part this is just doing Python operations which does not fit in with the rest of the code which works builds Pyomo models. Could you clarify the purpose of this code a bit more?

2024-04-26 13:58 UTC, andrewlee94 commented on src/prommis/leaching/tests/test_leach_flowsheet.py
> +    assert_optimal_termination,
Why is this file being edited here? These changes are just ordering of imports, and the original import order is more correct.

2024-04-26 13:58 UTC, andrewlee94 commented on src/prommis/uky/costing/ree_plant_capcost.py
> +from pyomo.common.dependencies import attempt_import
Similarly, these changes seem to be unrelated to this PR.

2024-04-26 13:58 UTC, andrewlee94 commented on src/prommis/uky/costing/tests/test_ree_costing.py
> +from pyomo.common.dependencies import attempt_import
Again, at first glance this does not appear to be related to this PR.

2024-04-26 14:03 UTC, bpaul4 commented
@Akintomiwaojo thank you for opening this. Before @andrewlee94's addressing comments above, the branch is very out-of-date and should be updated. Please resolve any merge conflicts when doing so.

2024-04-29 13:30 UTC, closed without merging

2024-04-29 13:31 UTC, Akintomiwaojo commented
As suggested, I will push this to the PrOMMiS workspace.